//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectionInfo", ReplyAction="http://tempuri.org/IService1/ConnectionInfoResponse")]
        void ConnectionInfo(string name, string port, string localPath, string uri, string scheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectionInfo", ReplyAction="http://tempuri.org/IService1/ConnectionInfoResponse")]
        System.Threading.Tasks.Task ConnectionInfoAsync(string name, string port, string localPath, string uri, string scheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountOfDBRows", ReplyAction="http://tempuri.org/IService1/CountOfDBRowsResponse")]
        void CountOfDBRows(string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountOfDBRows", ReplyAction="http://tempuri.org/IService1/CountOfDBRowsResponse")]
        System.Threading.Tasks.Task CountOfDBRowsAsync(string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMethod", ReplyAction="http://tempuri.org/IService1/InsertMethodResponse")]
        string InsertMethod(string id_exp, string id_h, string date, string autor_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMethod", ReplyAction="http://tempuri.org/IService1/InsertMethodResponse")]
        System.Threading.Tasks.Task<string> InsertMethodAsync(string id_exp, string id_h, string date, string autor_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataTable GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecCheck", ReplyAction="http://tempuri.org/IService1/RecCheckResponse")]
        string RecCheck(string id_exp, string id_h, string date, string autor_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecCheck", ReplyAction="http://tempuri.org/IService1/RecCheckResponse")]
        System.Threading.Tasks.Task<string> RecCheckAsync(string id_exp, string id_h, string date, string autor_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpSelectData", ReplyAction="http://tempuri.org/IService1/GetExpSelectDataResponse")]
        System.Data.DataTable GetExpSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpSelectData", ReplyAction="http://tempuri.org/IService1/GetExpSelectDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetExpSelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHallSelectData", ReplyAction="http://tempuri.org/IService1/GetHallSelectDataResponse")]
        System.Data.DataTable GetHallSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHallSelectData", ReplyAction="http://tempuri.org/IService1/GetHallSelectDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHallSelectDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebClient.ServiceReference1.IService1>, WebClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void ConnectionInfo(string name, string port, string localPath, string uri, string scheme) {
            base.Channel.ConnectionInfo(name, port, localPath, uri, scheme);
        }
        
        public System.Threading.Tasks.Task ConnectionInfoAsync(string name, string port, string localPath, string uri, string scheme) {
            return base.Channel.ConnectionInfoAsync(name, port, localPath, uri, scheme);
        }
        
        public void CountOfDBRows(string count) {
            base.Channel.CountOfDBRows(count);
        }
        
        public System.Threading.Tasks.Task CountOfDBRowsAsync(string count) {
            return base.Channel.CountOfDBRowsAsync(count);
        }
        
        public string InsertMethod(string id_exp, string id_h, string date, string autor_order) {
            return base.Channel.InsertMethod(id_exp, id_h, date, autor_order);
        }
        
        public System.Threading.Tasks.Task<string> InsertMethodAsync(string id_exp, string id_h, string date, string autor_order) {
            return base.Channel.InsertMethodAsync(id_exp, id_h, date, autor_order);
        }
        
        public System.Data.DataTable GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public string RecCheck(string id_exp, string id_h, string date, string autor_order) {
            return base.Channel.RecCheck(id_exp, id_h, date, autor_order);
        }
        
        public System.Threading.Tasks.Task<string> RecCheckAsync(string id_exp, string id_h, string date, string autor_order) {
            return base.Channel.RecCheckAsync(id_exp, id_h, date, autor_order);
        }
        
        public System.Data.DataTable GetExpSelectData() {
            return base.Channel.GetExpSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetExpSelectDataAsync() {
            return base.Channel.GetExpSelectDataAsync();
        }
        
        public System.Data.DataTable GetHallSelectData() {
            return base.Channel.GetHallSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHallSelectDataAsync() {
            return base.Channel.GetHallSelectDataAsync();
        }
    }
}
